// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5114.MyRobot2017.subsystems;

import org.usfirst.frc5114.MyRobot2017.Robot;
import org.usfirst.frc5114.MyRobot2017.RobotMap;
import org.usfirst.frc5114.MyRobot2017.commands.*;
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class TankDriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon cANTalon1 = RobotMap.driveTrainCANTalon1;
    private final CANTalon cANTalon2 = RobotMap.driveTrainCANTalon2;
    private final CANTalon cANTalon3 = RobotMap.driveTrainCANTalon3;
    private final CANTalon cANTalon4 = RobotMap.driveTrainCANTalon4;
//    private final CANTalon cANTalon5 = RobotMap.intakeBallCANTalon5;
//    private final CANTalon cANTalon6 = RobotMap.intakeBallCANTalon5;
    
private final RobotDrive robotDrive41 = RobotMap.driveTrainRobotDrive4;
    
    private double power = 0.8;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    	setDefaultCommand(new DriveWithJoysticks());
    }
    
    public void takeJoystickInputs(Joystick left, Joystick right) 
    {
    	robotDrive41.tankDrive(left, right);
    }
    
    public void driveNorth(double percentVolt)
    {
    	power = percentVolt;
    	cANTalon3.set(power);
    	cANTalon1.set(-power);
    }
    
    public void driveSouth(double percentVolt)
    {
    	power = -percentVolt;
    	cANTalon3.set(power);
    	cANTalon1.set(-power);
    }
    
    public void stop()
    {
    	robotDrive41.drive(0, 0);
    }
}

